"""Generated optical-power calibration constants.

Generated by optical-power calibration tooling.
Model: sin2
"""

from __future__ import annotations

from awgsegmentfactory.calibration import AODSin2Calib, AWGCalibration

# source: H='examples/calibrations/814_H_calFile_17.02.2022_0=0.txt'
CALIB_814_CALFILE_17_02_2022_0_0_H = AODSin2Calib(
    g_poly_high_to_low=(
        0.4090989912253647,
        0.2018618742515838,
        -0.9215927915167634,
        -0.4412476500516808,
        -0.1906036583947077,
        -0.03972136086542679,
        1.177618710972786,
    ),
    v0_a_poly_high_to_low=(
        -206.7523109846387,
        -51.19251677219333,
        328.8140960804296,
        66.80024091181865,
        -142.5622869379855,
        -11.97940312739627,
        199.7834400057718,
    ),
    freq_min_hz=80000000,
    freq_max_hz=120000000,
    traceability_string="examples/calibrations/814_H_calFile_17.02.2022_0=0.txt",
    amp_scale=0.005882352941176471,
    min_g=1e-12,
    min_v0_sq=1e-09,
    y_eps=1e-06,
)

# source: V='examples/calibrations/814_V_calFile_17.02.2022_0=0.txt'
CALIB_814_CALFILE_17_02_2022_0_0_V = AODSin2Calib(
    g_poly_high_to_low=(
        0.1476077059082392,
        -0.03982795249054526,
        -0.6737338878355211,
        -0.02778152984507814,
        0.3370885748323629,
        0.02326850145597811,
        0.9935230408830742,
    ),
    v0_a_poly_high_to_low=(
        -155.0879927769708,
        -49.22556216836927,
        253.8100155943833,
        63.78042793848495,
        -98.59810691776225,
        -12.31066136792399,
        151.8124648021865,
    ),
    freq_min_hz=80000000,
    freq_max_hz=120000000,
    traceability_string="examples/calibrations/814_V_calFile_17.02.2022_0=0.txt",
    amp_scale=0.005882352941176471,
    min_g=1e-12,
    min_v0_sq=1e-09,
    y_eps=1e-06,
)

CALIB_814_CALFILE_17_02_2022_0_0 = AWGCalibration(
    N_ch=2,
    logical_to_hardware_map={"H": 0, "V": 1},
    channel_calibrations=(CALIB_814_CALFILE_17_02_2022_0_0_H, CALIB_814_CALFILE_17_02_2022_0_0_V),
)

# source: *='examples/calibrations/AWG1_calibration_22_02_2023_90MHz_255MHz.awgde'
AWG1_CALIBRATION_22_02_2023_90MHZ_255MHZ = AODSin2Calib(
    g_poly_high_to_low=(
        4.0810642145489,
        6.464262432447331,
        0.8376298359479603,
        -4.905461659062055,
        -5.107324338374034,
        0.5794154762093924,
        2.416680489478826,
    ),
    v0_a_poly_high_to_low=(
        -4138.355365747419,
        458.1478438649602,
        6630.064610798006,
        895.90646690625,
        -1213.218415540377,
        -10.72565578610046,
        274.8991594708095,
    ),
    freq_min_hz=90000000,
    freq_max_hz=251000000,
    traceability_string="examples/calibrations/AWG1_calibration_22_02_2023_90MHz_255MHz.awgde",
    amp_scale=0.003999999999999999,
    min_g=1e-12,
    min_v0_sq=1e-09,
    y_eps=1e-06,
)

# source: *='examples/calibrations/AWG3_calibration_04_10_2024_98MHz_118MHz.awgde'
AWG3_CALIBRATION_04_10_2024_98MHZ_118MHZ = AODSin2Calib(
    g_poly_high_to_low=(
        -0.8380834486577289,
        -0.01211634279966487,
        2.684175895919575,
        0.3922012330343838,
        -3.016086026356905,
        -0.5164595332474879,
        1.379883806047519,
    ),
    v0_a_poly_high_to_low=(
        209.4474772492902,
        128.6140737328884,
        -246.4265700329758,
        -166.0422129338404,
        25.63398672025559,
        63.73744831391763,
        375.7907650917821,
    ),
    freq_min_hz=85000000,
    freq_max_hz=135000000,
    traceability_string="examples/calibrations/AWG3_calibration_04_10_2024_98MHz_118MHz.awgde",
    amp_scale=0.002631578947368421,
    min_g=1e-12,
    min_v0_sq=1e-09,
    y_eps=1e-06,
)

CALIBS_BY_DATASET_KEY: dict[str, AODSin2Calib | AWGCalibration] = {
    "814_calFile_17.02.2022_0=0": CALIB_814_CALFILE_17_02_2022_0_0,
    "AWG1_calibration_22_02_2023_90MHz_255MHz": AWG1_CALIBRATION_22_02_2023_90MHZ_255MHZ,
    "AWG3_calibration_04_10_2024_98MHz_118MHz": AWG3_CALIBRATION_04_10_2024_98MHZ_118MHZ,
}
